language: node_js
node_js:
  - "4.2.1"
cache:
  directories:
    - node_modules
    - bower_components
before_script:
  - npm install -g gulp
  - npm install -g bower
script: 
  - bower install
  - gulp build
